require('dotenv').config({path: __dirname + '/./../../../../.env'});

const {
  PRODUCTCATALOGUE_NODE_ENV,
  PRODUCTCATALOGUE_PROD_PORT,

  PRODUCTCATALOGUE_PROD_DATABASE_USERNAME,
  PRODUCTCATALOGUE_PROD_DATABASE_PASSWORD,
  PRODUCTCATALOGUE_PROD_DATABASE_NAME,
  PRODUCTCATALOGUE_PROD_DATABASE_HOST,
  PRODUCTCATALOGUE_PROD_DATABASE_URL,
  PRODUCTCATALOGUE_PROD_DATABASE_DIALECT,
  
} = process.env;


module.exports = {
  PRODUCTCATALOGUE_NODE_ENV,
  PRODUCTCATALOGUE_PORT: PRODUCTCATALOGUE_PROD_PORT,

  PRODUCTCATALOGUE_DATABASE_USERNAME: PRODUCTCATALOGUE_PROD_DATABASE_USERNAME,
  PRODUCTCATALOGUE_DATABASE_PASSWORD: PRODUCTCATALOGUE_PROD_DATABASE_PASSWORD,
  PRODUCTCATALOGUE_DATABASE_NAME: PRODUCTCATALOGUE_PROD_DATABASE_NAME,
  PRODUCTCATALOGUE_DATABASE_HOST: PRODUCTCATALOGUE_PROD_DATABASE_HOST,
  PRODUCTCATALOGUE_DATABASE_URL: PRODUCTCATALOGUE_PROD_DATABASE_URL,
  PRODUCTCATALOGUE_DATABASE_DIALECT: PRODUCTCATALOGUE_PROD_DATABASE_DIALECT,
};